// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Maf_NodeRequest_FullMethodName = "/Maf/NodeRequest"
	Maf_Reply_FullMethodName       = "/Maf/Reply"
)

// MafClient is the Nodes API for Maf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MafClient interface {
	NodeRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Reply(ctx context.Context, in *Response, opts ...grpc.CallOption) (*RecievedResponseButEmpty, error)
}

type mafClient struct {
	cc grpc.ClientConnInterface
}

func NewMafClient(cc grpc.ClientConnInterface) MafClient {
	return &mafClient{cc}
}

func (c *mafClient) NodeRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Maf_NodeRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mafClient) Reply(ctx context.Context, in *Response, opts ...grpc.CallOption) (*RecievedResponseButEmpty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecievedResponseButEmpty)
	err := c.cc.Invoke(ctx, Maf_Reply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MafServer is the server API for Maf service.
// All implementations must embed UnimplementedMafServer
// for forward compatibility.
type MafServer interface {
	NodeRequest(context.Context, *Request) (*Response, error)
	Reply(context.Context, *Response) (*RecievedResponseButEmpty, error)
	mustEmbedUnimplementedMafServer()
}

// UnimplementedMafServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMafServer struct{}

func (UnimplementedMafServer) NodeRequest(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeRequest not implemented")
}
func (UnimplementedMafServer) Reply(context.Context, *Response) (*RecievedResponseButEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reply not implemented")
}
func (UnimplementedMafServer) mustEmbedUnimplementedMafServer() {}
func (UnimplementedMafServer) testEmbeddedByValue()             {}

// UnsafeMafServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MafServer will
// result in compilation errors.
type UnsafeMafServer interface {
	mustEmbedUnimplementedMafServer()
}

func RegisterMafServer(s grpc.ServiceRegistrar, srv MafServer) {
	// If the following call pancis, it indicates UnimplementedMafServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Maf_ServiceDesc, srv)
}

func _Maf_NodeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MafServer).NodeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maf_NodeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MafServer).NodeRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maf_Reply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Response)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MafServer).Reply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maf_Reply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MafServer).Reply(ctx, req.(*Response))
	}
	return interceptor(ctx, in, info, handler)
}

// Maf_ServiceDesc is the grpc.ServiceDesc for Maf service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Maf_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Maf",
	HandlerType: (*MafServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeRequest",
			Handler:    _Maf_NodeRequest_Handler,
		},
		{
			MethodName: "Reply",
			Handler:    _Maf_Reply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
